version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./simple_flask_app:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock